# Bruker MySQL 8.0 som base-image
FROM mysql:8.0

# Kopierer init.sql til containerens oppstartsmappe
COPY init.sql /docker-entrypoint-initdb.d/

# Setter miljøvariabler for MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Eksponer MySQL-porten
EXPOSE 3306
